### ISSUE TITLE
Extract min node doesn't work properly

### ISSUE THREAD

**Issue by emmariaolsson** [JohanKJIP/algorithms#25]
Testcase:

min_heap = FibonacciHeap()
min_heap.insert(4)
min_heap.insert(50)
min_heap.insert(7)
min_heap.insert(55)
min_heap.extract_min_node()
min_heap.insert(90)
min_heap.insert(87)

Should have a tree structure after extract method. Output:

`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/emmaolsson/algorithms/algorithms/heap/fibonacci_heap.py", line 319, in <module>
    main()
  File "/Users/emmaolsson/algorithms/algorithms/heap/fibonacci_heap.py", line 312, in main
    min_heap.extract_min_node()
  File "/Users/emmaolsson/algorithms/algorithms/heap/fibonacci_heap.py", line 168, in extract_min_node
    self._consolidate()
  File "/Users/emmaolsson/algorithms/algorithms/heap/fibonacci_heap.py", line 179, in _consolidate
    root_nodes = [x for x in self._iterate(self.root_list)]
  File "/Users/emmaolsson/algorithms/algorithms/heap/fibonacci_heap.py", line 179, in <listcomp>
    root_nodes = [x for x in self._iterate(self.root_list)]
  File "/Users/emmaolsson/algorithms/algorithms/heap/fibonacci_heap.py", line 96, in _iterate
    node = node.right
KeyboardInterrupt`

**Comment by jvonhacht** [comment]
Fixat nu tror jag i den senaste versionen.
